# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ad5cb87a25dd25b2ead4433a65c1cb63b57f301b1f0aed8b5f4d352d190645bd75c092d7a745e97791687c0c1fafcafaae8967faf583ec37419245351e3b2508

test:
  secret_key_base: 21afba2dd40f5a355f777a523d4d15b3e4757ea1b66a38d59dd9674ecf62eb2f89dfad33e3d8cb8f8b7c95565a1879a47e4f663ab33b46129e2c19ae37b9877b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
